export const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
  STAFF: 'STAFF'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
};

export const ORDER_STATUS = {
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  KYC_PENDING: 'KYC_PENDING',
  KYC_VERIFICATION: 'KYC_VERIFICATION',
  KYC_VERIFIED: 'KYC_VERIFIED',
  PROCESSING: 'PROCESSING',
  CA_PROCESSING: 'CA_PROCESSING',
  ISSUED: 'ISSUED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const KYC_STATUS = {
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  REUPLOAD_REQUIRED: 'REUPLOAD_REQUIRED'
};

export const DSC_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_CA_QUEUE: 'IN_CA_QUEUE',
  ISSUED: 'ISSUED',
  DISPATCHED: 'DISPATCHED'
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};

export const PRODUCT_CATEGORIES = {
  CLASS_3_INDIVIDUAL: 'CLASS_3_INDIVIDUAL',
  CLASS_3_ORGANIZATION: 'CLASS_3_ORGANIZATION',
  DGFT: 'DGFT',
  ETENDER: 'ETENDER',
  MCA: 'MCA',
  DOCUMENT_SIGNER: 'DOCUMENT_SIGNER'
};

export const DOCUMENT_TYPES = {
  PAN_CARD: 'PAN_CARD',
  AADHAAR_FRONT: 'AADHAAR_FRONT',
  AADHAAR_BACK: 'AADHAAR_BACK',
  PASSPORT: 'PASSPORT',
  PHOTO: 'PHOTO',
  GST_CERTIFICATE: 'GST_CERTIFICATE',
  BOARD_RESOLUTION: 'BOARD_RESOLUTION',
  AUTHORIZATION_LETTER: 'AUTHORIZATION_LETTER'
};

export const NOTIFICATION_CHANNELS = {
  IN_APP: 'IN_APP',
  WHATSAPP: 'WHATSAPP',
  EMAIL: 'EMAIL',
  SMS: 'SMS'
};

export const SUPPORT_TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_CUSTOMER: 'WAITING_FOR_CUSTOMER',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

export const GST_RATE = 0.18; // 18% GST (9% CGST + 9% SGST / 18% IGST)
export const USB_TOKEN_PRICE = 500; // INR 500 for cryptographic FIPS 140-2 token
